# Generated by Django 3.2.9 on 2022-02-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contacto_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='image',
        ),
    ]
